export {default as Talent} from './talent.svg';
export {default as Performance} from './performance.svg'
export {default as Staff} from './staff.svg';
export {default as Employer} from './employer.svg';
export {default as Employee} from './employee.svg';
export {default as Attendance} from './attendance.svg';
export {default as Core} from './core.svg';
export {default as Payroll} from './payroll.svg';
export {default as HeroManOne} from './hero-man-one.png';
export {default as HeroManTwo} from './hero-man-two.png';
export {default as Woman} from './hero-woman.png';