export {default as imgOne} from './imgOne.png'
export {default as imgTwo} from './imgTwo.png'
export {default as imgThree} from './imgThree.png'
export {default as imgFour} from './imgFour.png'
export {default as imgFive} from './imgFive.png'